# Generated by Django 6.0.4 on 2026-05-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('progress', 'В работе'), ('done', 'Завершена')], default='new', max_length=10),
        ),
    ]
